export namespace NotificationProviderEnum {
  export const CONSUMERS = {
    ACCOUNT_CREATED_NOTIFICATION: Symbol('ACCOUNT_CREATED_NOTIFICATION'),
    RESET_PASSWORD_NOTIFICATION: Symbol('RESET_PASSWORD_NOTIFICATION'),
    WELCOME_NOTIFICATION: Symbol('WELCOME_NOTIFICATION'),
  } as const
}
