export namespace AccountProviderEnum {
  export const COMMANDS = {
    LOGIN: Symbol('LOGIN'),
    GENERATE_REFRESH_TOKEN: Symbol('GENERATE_REFRESH_TOKEN'),
    LOGOUT: Symbol('LOGOUT'),
    CREATE_ACCOUNT: Symbol('CREATE_ACCOUNT'),
    VALIDATE_SECURITY_TOKEN: Symbol('VALIDATE_SECURITY_TOKEN'),
    CONFIRM_ACCOUNT: Symbol('CONFIRM_ACCOUNT'),
    RESEND_ACCOUNT_CONFIRMATION: Symbol('RESEND_ACCOUNT_CONFIRMATION'),
    REQUEST_RESET_PASSWORD: Symbol('REQUEST_RESET_PASSWORD'),
    CONFIRM_PASSWORD_RESET: Symbol('CONFIRM_PASSWORD_RESET'),
    DELETE_ACCOUNT: Symbol('DELETE_ACCOUNT'),
  } as const
  export const QUERIES = {
    GET_USER: Symbol('GET_USER'),
    EXPORT_USER_DATA: Symbol('EXPORT_USER_DATA'),
  } as const
}
